
title: Lab Notebook 
tagline: Theoretical ecology and evolution
author:
  name: Carl Boettiger
  givenName: Carl
  familyName: Boettiger
  twitter: cboettig
  github: cboettig
  mendeley: carl-boettiger
  email: cboettig@gmail.com
url: http://www.carlboettiger.info
baseurl: /2015
username: cboettig

gems:
  - jekyll-pandoc

encoding: utf-8

## Markdown Parser 
markdown: pandoc
markdown_ext:  markdown,md #,Rmd,rmd
pandoc:
  extensions: 
    - smart
    - mathjax
#    - template: 'assets/datauri_template.html'   # Use with 'self-contained' to avoid header text in body
#    - self-contained                             # Archive images in posts as URIs.  Very slow, for archiving only.  
#    - mathml                                     # Use mathml for equations (Archival, HTML5/XML valid syntax)


permalink: /:month/:day/:title.html
pageviews: no    ## toggle on sidebar pageviews 
twitter_api: yes
analytics: UA-18401403-1 ## Google Analytics key (in _includes/analytics.html)


exclude:
  - _posts/*.Rmd
  - build.R
  - _deploy.sh
  - _build.sh
  - .drone.yml
  - tmp/
  - tmp/cache
