---
layout: post
category: ecology
tags:
  - earlywarning
code: true
---


```{r settings, include=FALSE}
library(knitr)
opts_chunk$set(dev='png', fig.width=3, fig.height=3, cache=1,results='hide')
```


some sample data from earlywarning:

```{r}
library(nimble)
library(earlywarning)
set.seed(123)
data(ibms)
plot(ibm_critical)
data <- as.data.frame(ibm_critical)
names(data) <- "x"
```



## LSN version ##

```{r}
lsn <- nimbleCode({
   theta ~ dunif(1e-10, 100.0)
   sigma_x ~ dunif(1e-10, 100.0)
   sigma_y ~ dunif(1e-10, 100.0)
       m ~ dunif(-1e2, 1e2)
    x[1] ~ dunif(0, 100)
    y[1] ~ dunif(0, 100) 

  for(i in 1:(N-1)){
    mu_x[i] <- x[i] + y[i] * (theta - x[i]) 
    x[i+1] ~ dnorm(mu_x[i], sd = sigma_x) 
    mu_y[i] <- y[i] + m * t[i]
    y[i+1] ~ dnorm(mu_y[i], sd = sigma_y) 
  }
})
```

Constants in the model definition are the length of the dataset, $N$ and the time points of the sample. Note we've made time explicit, we'll assume uniform spacing here. 

```{r}
constants <- list(N = length(data[[1]]), t = 1:length(data[[1]]))
```

Initial values for the parameters

```{r}
inits <- list(theta = 6, m = 0, sigma_x = 1, sigma_y = 1, y = rep(1,constants$N))
```


and here we go:

```{r}
Rmodel <- nimbleModel(code = lsn, 
                      constants = constants, 
                      data = data, 
                      inits = inits)
Cmodel <- compileNimble(Rmodel)
```



```{r, echo=TRUE, results = 'hide', message = FALSE}
mcmcspec <- configureMCMC(Rmodel, print=TRUE,thin=2e2)
Rmcmc <- buildMCMC(mcmcspec)
Cmcmc <- compileNimble(Rmcmc, project = Cmodel)
```


```{r} 
Cmcmc$run(1e6)
```


and examine results

```{r}
samples <- as.data.frame(as.matrix(Cmcmc$mvSamples))
dim(samples)
samples <- samples[,1:4]
```


```{r}
mean(samples$theta)
mean(samples$m)
mean(samples$sigma_x)
```




```{r fig.show='hold'}
plot(samples[ , 'm'], type = 'l', xlab = 'iteration', ylab = 'm', main='')
plot(samples[ , 'sigma_x'], type = 'l', xlab = 'iteration', ylab = expression(sigma[x]), main='')
plot(samples[ , 'sigma_y'], type = 'l', xlab = 'iteration', ylab = expression(sigma[y]), main='')
plot(samples[ , 'theta'], type = 'l', xlab = 'iteration', ylab = expression(theta), main='')
```

```{r fig.show='hold'}
hist(samples[, 'm'], xlab = 'm', main='')
hist(samples[, 'sigma_x'], xlab = expression(sigma[x]), main='')
hist(samples[, 'sigma_y'], xlab = expression(sigma[y]), main='')
hist(samples[, 'theta'], xlab = expression(theta), main='')
```



```{r results='markup'}
sessionInfo()
```
