---
published: false
layout: post
category: ecology
tags: 
- early-warning
- regime-shifts

---





```{r include=FALSE, cache=FALSE}
library("nimble")
library("ggplot2")
```



## dmnorm example ##

from Daniel:

```{r}
code <- nimbleCode({
    mu ~ dunif(-100, 100)
    sigma ~ dunif(0, 100)
    rho ~ dunif(20, 100)
    muVec[1:N] <- mu * onesVector[1:N]
    Cov[1:N, 1:N] <- sigma^2 * exp(-dist[1:N, 1:N]/rho)
    g[1:N] ~ dmnorm(muVec[1:N], cov = Cov[1:N, 1:N])
    for (i in 1:N) {
        y[i] ~ dpois(exp(g[i]))
    }
})

constants <- list(N = 148, 
                  onesVector = rep(1, 148), 
                  dist = matrix(1, nrow=148, ncol=148))

y = rpois(148, 1) # vector of 148 observations (counts)
data <- list(y=y)

inits <- list(mu = 0, 
              sigma = 5, 
              rho = 60, 
              g = rep(0, 148))

m <- nimbleModel(code = code, constants = constants, data = data, inits = inits)
```

## GP Model ##

```{r}

obs <- data.frame(x = c(-4, -3, -1,  0,  2),
                   y = c(-2,  0,  1,  2, -1))

code <- nimbleCode({

   l ~ dgamma(5, 5)
   sigma.n ~ dgamma(5, 5)
  
   SE <- function(xi,xj, l) exp(-0.5 * (xi - xj) ^ 2 / l ^ 2)
   Mu <- rep(0, N)
   Sigma <- outer(x[1:N], x[1:N], SE, l) + sigma.n ^ 2 * diag(1, N)
   Lambda <- solve(Sigma)
   y[1:N] ~ dmnorm(Mu, Lambda)  

})

constants = list(N = length(obs$x), x = obs$x)
inits <- list(l = 1, sigma.n = 10)
data <- data.frame(y = obs$y)
```


```{r}
  Rmodel <- nimbleModel(code = code, constants = constants, data = data, inits = inits)
```

Define our mcmc procedure in Nimble

```{r }
my_mcmc <- function(code, constants, data, inits, n_iter=1e5, thin = 1e2){
  
  Rmodel <- nimbleModel(code = code, constants = constants, data = data, inits = inits)
  Cmodel <- compileNimble(Rmodel)
  mcmcspec <- configureMCMC(Rmodel, print=FALSE,thin=thin)
  Rmcmc <- buildMCMC(mcmcspec)
  Cmcmc <- compileNimble(Rmcmc, project = Cmodel)
  Cmcmc$run(n_iter)
  samples <- as.data.frame(as.matrix(Cmcmc$mvSamples))
  samples <- samples[,1:(length(inits)-1)]
  gather(samples)
}
```




## sample data

```{r}
f <- function (x, p){ x * exp(p[1] * (1 - x / p[2]) * (x - p[3]) / p[2]) }
p <- c(2, 8, 5)
z_g <- function() rlnorm(1, 0, 0.05)
N <- 40

set.seed(1234)
x <- numeric(N)
x[1] <- 5.5

for(t in 1:(N-1))
  x[t+1] = z_g() * f(x[t], p=p)

qplot(seq_along(x), x)
data <- data.frame(x=x)

```


```{r }
# library("nonparametricbayes")
#gp <- gp_mcmc(obs$x, y = obs$y, n = 1e5, s2.p = c(5,5), d.p = c(10,10))
```



```{r message=FALSE}
df <- my_mcmc(code=ou, ou_constants, data, ou_inits)
```


#### Summary statistics

```{r , results='markup'}
summarise(group_by(df, key), mean=mean(value), std=sqrt(var(value)))
```

#### Traces

```{r , fig.show='hold'}
ggplot(df) + 
  geom_line(aes(seq_along(value), value)) + 
  facet_wrap(~key, scale='free')
```

#### Posteriors

```{r , fig.show='hold'}
ggplot(df) + 
  geom_density(aes(value)) + 
  facet_wrap(~key, scale='free')
```




