---
published: false
layout: post
category: ecology
tags: 
- gp
- nimble

---

```{r }
library("MASS")
library("mcmc")
library("nimble")
library("ggplot2")
library("tidyr")
library("dplyr")

knitr::opts_chunk$set(eval=FALSE)
```

## sample data ##

```{r}
set.seed(1234)
Tobs <- 40
f <- function(x, h, p){ 
    x <- pmax(0,x-h)
    x * exp(p[1] * (1 - x / p[2]) * (x - p[3]) / p[2] ) 
}
p <- c(2, 8, 5)
x <- numeric(Tobs)
x[1] <- 5.5
nz <- 1
for(t in 1:(Tobs-1))
  x[t+1] = rlnorm(1, 0, 0.05) * f(x[t], h=0, p=p)
obs <- data.frame(x = c(rep(0,nz), 
                        pmax(rep(0,Tobs-1), x[1:(Tobs-1)])), 
                  y = c(rep(0,nz), 
                        x[2:Tobs]))
ggplot(data.frame(time = 1:Tobs, x=x), aes(time,x)) + geom_line()
```

## GP Model ##


```{r}
code <- nimbleCode({

   l ~ dgamma(10, 1) 
   sigma.n ~ dunif(0, 1e5)
   sigma.k  ~ dunif(0, 1e5)
   Sigma[1:N, 1:N] <- sigma.k ^ 2 * exp(-0.5 * diff[1:N, 1:N] / l ^ 2) + 
                      sigma.n ^ 2 * I[1:N, 1:N]
   y[1:N] ~ dmnorm(Mu[1:N], cov = Sigma[1:N, 1:N])  

})
```


```{r}
N <- length(obs$x)
diff <- outer(obs$x, obs$x, function(xi, xj) (xi-xj)^2)
constants = list(N = N, x = obs$x, Mu = rep(0,N), diff = diff, I = diag(1,N))
inits <- list(l = 1, sigma.n = 10)
data <- data.frame(y = obs$y)


```

```{r}
Rmodel <- nimbleModel(code = code, constants = constants, data = data, inits = inits)
```


Define our mcmc procedure in Nimble

```{r }
Cmodel <- compileNimble(Rmodel)
mcmcspec <- configureMCMC(Rmodel, print=FALSE)
Rmcmc <- buildMCMC(mcmcspec)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)
```

```{r}
system.time(
Cmcmc$run(1e5)
)
```

```{r}
samples <- as.data.frame(as.matrix(Cmcmc$mvSamples))
df <- gather(samples)
```


#### Posteriors

```{r , fig.show='hold'}
ggplot(df) + 
  geom_density(aes(value)) + 
  facet_wrap(~key, scale='free')
```


--------------------------------------------

## Comparison

```{r}

 lpriors <- function(pars){
      dgamma(pars[[1]], 10, 1, log = TRUE) +
      dunif(pars[[2]], 0, 1e5, log = TRUE) 
  }
  
  posterior <- function(pars, x, y){ 
    l <- pars[1]
    sigma.n <- pars[2]

    SE <- function(Xi,Xj, l) exp(-0.5 * (Xi - Xj) ^ 2 / l ^ 2)
    cov <- function(X, Y) outer(X, Y, SE, l)
    I <- diag(1, length(x))
    K <- cov(x, x) 
  
    loglik <- - 0.5 * t(y) %*% solve(K + sigma.n ^ 2 * I) %*% y -
      log(det(K + sigma.n ^ 2 * I)) -
      length(y) * log(2 * pi) / 2
    
    loglik + lpriors(pars)
  }
```

```{r}
system.time(
out <- metrop(posterior, initial = c(l = 1,sigma.n = 10), nbatch = 1e5, x = obs$x, y = obs$y)  
)
```

```{r}
burnin <- 1e3
thin <- 1e2
df <- cbind(index=1:out$nbatch, as.data.frame(exp(out$batch)))
s <- seq(burnin+1, out$nbatch, by=thin)
df <- df[s,]
df <- df[-1] # drop index
names(df) <- names(out$initial)
df <- gather(df)
```


```{r}
ggplot(df) + 
  geom_density(aes(value)) + 
  facet_wrap(~key, scale='free') +
  scale_x_log10()
```

