---
layout: post
tags:
- reading
- docker
---

## more user craziness with docker 

Should do something about rstudio script when running as a non-root user.... Fixed! Requires changing user more carefully; we cannot simply delete the existing user. 

When using a docker image with a non-root default user, we can launch a container as root by
giving root's UID instead with the `--user 0` flag.  (Note that we can do this with other UIDs
as well, though it produces a troublesome unnamed user when the userid hasn't been assigned
to a user name).

- RStudio image now completely configures default user in the Dockerfile, such that userconf.sh need only configure custom users. See [userconf.sh](https://github.com/rocker-org/rocker/blob/cec3912d3bc40352fc4ca7d7d281db9e25b3dd86/rstudio/userconf.sh). We now do:

```
usermod -l rstudio docker \
	&& usermod -m -d /home/rstudio rstudio \
	&& groupmod -n rstudio docker 
```

instead of `userdel` which causes issues if we launch as that user.  Note, this means containers built on `rstudio` have only the user `rstudio` available and not the `docker` user, unless explicitly added/renamed.  Avoids issues like multiple home directories/unpredictable home directory name as well (Since RStudio-server wants to open in home dir and not in a user-owned root directory like `/data` like most other apps would use.)
- RStudio must still be launched as root (see [RStudio issue](https://support.rstudio.com/hc/communities/public/questions/200661923-Does-Rstudio-have-to-run-as-root-)), so a Dockerfile with non-root user must use the `--user 0` flag or run `rserver` or the default `supervisord` using `sudo`.  
- Configure [supervisord.conf](https://github.com/rocker-org/rocker/blob/cec3912d3bc40352fc4ca7d7d281db9e25b3dd86/rstudio/supervisord.conf) configuration not to throw erroneous error messages (e.g. `userconf.sh` is expected to exit with 0, users explicitly declared, config file explicitly declared to avoid security vulnerability of custom conf in working dir, etc).  



## Reading list notes 

Sebastian has a very nice reading list for his upcoming seminar on evolution in stochastic environments that I wanted to make note of for my own reference as well. 

Reading: Ruel, Jonathan J., and Matthew P. Ayres. "Jensen's inequality predicts effects of environmental variation." Trends in Ecology & Evolution 14.9 (1999): 361-366. Optional Reading: Frank, Steven A., and Montgomery Slatkin. "Evolution in a variable environment." American Naturalist (1990): 244-260.

BETWEEN-GENERATION BET-HEDGING

Week 2: Historical perspective and overview

Readings: Stearns, Stephen C. "Daniel Bernoulli (1738): evolution and economics under risk." Journal of biosciences 25.3 (2000): 221-228.
Childs, Dylan Z., C. J. E. Metcalf, and Mark Rees. "Evolutionary bet-hedging in the real world: empirical evidence and challenges revealed by plants." Proceedings of the Royal Society B: Biological Sciences (2010): rspb20100707. 
Optional Reading: Simons, Andrew M. "Modes of response to environmental change and the elusive empirical evidence for bet hedging." Proceedings of the Royal Society B: Biological Sciences (2011): rspb20110176.

Week 3: Seedbanks in annual plants
Readings: Venable, D. Lawrence. "Bet hedging in a guild of desert annuals." Ecology 88.5 (2007): 1086-1090; Gremer, Jennifer R., and D. Lawrence Venable. "Bet hedging in desert winter annual plants: optimal germination strategies in a variable environment." Ecology letters 17.3 (2014): 380-387.

Week 4: Stochastic switches, epigenetics, and bacteria

Readings: Beaumont, Hubertus JE, et al. "Experimental evolution of bet hedging." Nature 462.7269 (2009): 90-93; Veening, J. et al. "Bistability, Epigenetics, and Bet-Hedging in Bacteria." Annual Reviews of Microbiology (2008)

Week 5: Bet-hedging in structured populations

Potential readings:  Carja, Oana, Uri Liberman, and Marcus W. Feldman. "The evolution of phenotypic switching in subdivided populations." Genetics 196.4 (2014): 1185-1197; Pfister, Catherine A. "Patterns of variance in stage-structured populations: evolutionary predictions and ecological implications." Proceedings of the National Academy of Sciences 95.1 (1998): 213-218.; Schreiber, Sebastian J. "The evolution of patch selection in stochastic environments." The American Naturalist 180.1 (2012): 17-34.

WITHIN-GENERATION BET-HEDGING

Week 6: The idea and a perspective 
Readings:  Gillespie, John H. "Natural selection for within-generation variance in offspring number." Genetics 76.3 (1974): 601-606; Hopper, Keith R., et al. "Within-generation bet hedging: a seductive explanation?." Oikos 101.1 (2003): 219-222.

Week 7: Multiple matings in wasps and cooperative breeding in birds
Readings: Sarhan, Alia, and Hanna Kokko. "Multiple mating in the glanville fritillary butterfly: A case of within-generation bethedging?" Evolution 61.3 (2007): 606-616; Rubenstein, Dustin R "Spatiotemporal environmental variation, risk aversion, and the evolution of cooperative breeding as a bet-hedging strategy." Proceedings of the National Academy of Sciences 108.Supplement 2 (2011): 10816-10822.

Week 8: Synthesis of between- and within-generation bet-hedging
Readings: Starrfelt, Jostein, and Hanna Kokko. "Bet-hedging: a triple trade-off between means, variances and correlations." Biological Reviews 87.3 (2012): 742-755; Frank, Steven A. "Natural selection. I. Variable environments and uncertain returns on investment*." Journal of evolutionary biology 24.11 (2011): 2299-2309.

RESOURCE VARIATION AND RISK AVERSION

Week 9: Multiple limiting factors and ovule packaging in angiosperms
Readings: Rosenheim, Jay A., Uri Alon, and Guy Shinar. "Evolutionary Balancing of Fitness-Limiting Factors." The American Naturalist 175.6 (2010): 662-674. Burd, Martin, et al. "Ovule number per flower in a world of unpredictable pollination." American Journal of Botany 96.6 (2009): 1159-1167.



